version: '3'

tasks:
  build:
    cmds:
      - cd launchpad_app
  release-dev:
    dir: launchpad_app
    cmds:
      - flutter_distributor release --name dev
  generate-protobuf-code:
    dir: launchpad_app/lib/proto
    cmds:
      - protoc --dart_out=. .\BlizzardProductDb.proto
