; Automatically-generated file, do not edit manually.
#Include E:\Tools\Launchpad\Lib\Shared\AppException\AppException.ahk
#Include E:\Tools\Launchpad\Lib\Shared\AppException\FileSystemException.ahk
#Include E:\Tools\Launchpad\Lib\Shared\AppException\InvalidParameterException.ahk
#Include E:\Tools\Launchpad\Lib\Shared\AppException\MethodNotImplementedException.ahk
#Include E:\Tools\Launchpad\Lib\Shared\AppException\OperationFailedException.ahk
#Include E:\Tools\Launchpad\Lib\Shared\AppState\AppStateBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\AppState\JsonAppState.ahk
#Include E:\Tools\Launchpad\Lib\Shared\AppState\LaunchpadAppState.ahk
#Include E:\Tools\Launchpad\Lib\Shared\ArchiveFile\ArchiveFileBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\ArchiveFile\ZipArchive.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Cache\CacheBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Cache\FileCache.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Cache\ObjectCache.ahk
#Include E:\Tools\Launchpad\Lib\Shared\CLR\CLR.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Events\Events.ahk
#Include E:\Tools\Launchpad\Lib\Shared\ExeProcess\ExeProcess.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Game\BlizzardGame.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Game\GameBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Game\SimpleGame.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Gui\DialogBox.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Gui\FormGuiBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Gui\GuiBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Gui\ProgressIndicator.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Gui\SingleInputBox.ahk
#Include E:\Tools\Launchpad\Lib\Shared\GuiShape\ButtonShape.ahk
#Include E:\Tools\Launchpad\Lib\Shared\GuiShape\GuiShapeBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\HttpReq\HttpReqBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\HttpReq\WinHttpReq.ahk
#Include E:\Tools\Launchpad\Lib\Shared\IdGenerator\IdGeneratorBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\IdGenerator\UuidGenerator.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Installer\InstallerBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\InstallerComponent\DownloadableInstallerComponent.ahk
#Include E:\Tools\Launchpad\Lib\Shared\InstallerComponent\FileInstallerComponentBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\InstallerComponent\GitHubReleaseInstallerComponent.ahk
#Include E:\Tools\Launchpad\Lib\Shared\InstallerComponent\InstallerComponentBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Json\Json.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Launcher\LauncherBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Launcher\SimpleLauncher.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Notifier\NotifierBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Notifier\ToastNotifier.ahk
#Include E:\Tools\Launchpad\Lib\Shared\OpError\BasicOpError.ahk
#Include E:\Tools\Launchpad\Lib\Shared\OpError\OpErrorBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\OpStatus\BasicOpStatus.ahk
#Include E:\Tools\Launchpad\Lib\Shared\OpStatus\OpStatusBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Protobuf\Protobuf.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Service\ComponentServiceBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Service\EventManager.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Service\ServiceBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Theme\JsonTheme.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Theme\ThemeBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Toolbar\ToolbarBase.ahk
#Include E:\Tools\Launchpad\Lib\Shared\Vendor\Gdip_All.ahk
; End of auto-generated includes.
