; Automatically-generated file, do not edit manually.
#Include E:\Tools\Launchpad\Lib\Launchpad.ahk
#Include E:\Tools\Launchpad\Lib\ApiEndpoint\ApiEndpoint.ahk
#Include E:\Tools\Launchpad\Lib\ApiItem\ApiAsset.ahk
#Include E:\Tools\Launchpad\Lib\ApiItem\ApiDependency.ahk
#Include E:\Tools\Launchpad\Lib\ApiItem\ApiGame.ahk
#Include E:\Tools\Launchpad\Lib\ApiItem\ApiGameType.ahk
#Include E:\Tools\Launchpad\Lib\ApiItem\ApiItem.ahk
#Include E:\Tools\Launchpad\Lib\ApiItem\ApiLauncherType.ahk
#Include E:\Tools\Launchpad\Lib\ApiItem\ApiListing.ahk
#Include E:\Tools\Launchpad\Lib\ApiItem\ApiTypeItem.ahk
#Include E:\Tools\Launchpad\Lib\ApiItem\JsonItem.ahk
#Include E:\Tools\Launchpad\Lib\Builder\Builder.ahk
#Include E:\Tools\Launchpad\Lib\BuildFile\BuildFile.ahk
#Include E:\Tools\Launchpad\Lib\BuildFile\ComposableBuildFile.ahk
#Include E:\Tools\Launchpad\Lib\BuildFile\CopyableBuildFile.ahk
#Include E:\Tools\Launchpad\Lib\BuildFile\GameAhkFile.ahk
#Include E:\Tools\Launchpad\Lib\BuildFile\GameExeFile.ahk
#Include E:\Tools\Launchpad\Lib\BuildFile\IconFile.ahk
#Include E:\Tools\Launchpad\Lib\BuildFile\ShortcutFile.ahk
#Include E:\Tools\Launchpad\Lib\Cache\Cache.ahk
#Include E:\Tools\Launchpad\Lib\Cache\FileCache.ahk
#Include E:\Tools\Launchpad\Lib\Cache\ObjectCache.ahk
#Include E:\Tools\Launchpad\Lib\Config\AppConfig.ahk
#Include E:\Tools\Launchpad\Lib\Config\ConfigBase.ahk
#Include E:\Tools\Launchpad\Lib\Config\FileConfig.ahk
#Include E:\Tools\Launchpad\Lib\Config\IniConfig.ahk
#Include E:\Tools\Launchpad\Lib\Config\JsonConfig.ahk
#Include E:\Tools\Launchpad\Lib\Config\JsonWithDefaultsConfig.ahk
#Include E:\Tools\Launchpad\Lib\Config\LauncherConfig.ahk
#Include E:\Tools\Launchpad\Lib\Dependency\Dependency.ahk
#Include E:\Tools\Launchpad\Lib\Gui\DialogBox.ahk
#Include E:\Tools\Launchpad\Lib\Gui\FormWindow.ahk
#Include E:\Tools\Launchpad\Lib\Gui\GuiBase.ahk
#Include E:\Tools\Launchpad\Lib\Gui\LauncherEditor.ahk
#Include E:\Tools\Launchpad\Lib\Gui\MainWindow.ahk
#Include E:\Tools\Launchpad\Lib\Gui\ManageWindow.ahk
#Include E:\Tools\Launchpad\Lib\Gui\ProgressIndicator.ahk
#Include E:\Tools\Launchpad\Lib\Gui\SettingsWindow.ahk
#Include E:\Tools\Launchpad\Lib\Gui\SingleInputBox.ahk
#Include E:\Tools\Launchpad\Lib\Gui\ToolsWindow.ahk
#Include E:\Tools\Launchpad\Lib\HttpReq\HttpReq.ahk
#Include E:\Tools\Launchpad\Lib\LauncherGame\LauncherGame.ahk
#Include E:\Tools\Launchpad\Lib\Notifier\NotifierBase.ahk
#Include E:\Tools\Launchpad\Lib\Notifier\ToastNotifier.ahk
#Include E:\Tools\Launchpad\Lib\Service\CacheManager.ahk
#Include E:\Tools\Launchpad\Lib\Service\DependencyManager.ahk
#Include E:\Tools\Launchpad\Lib\Service\GuiService.ahk
#Include E:\Tools\Launchpad\Lib\Service\LauncherManager.ahk
#Include E:\Tools\Launchpad\Lib\Service\NotificationService.ahk
#Include E:\Tools\Launchpad\Lib\Service\ServiceBase.ahk
#Include E:\Tools\Launchpad\Lib\Toolbar\Toolbar.ahk
#Include E:\Tools\Launchpad\Lib\Vendor\Jxon.ahk
; End of auto-generated includes.
