; Automatically-generated file, do not edit manually.
#Include E:\Tools\Launchpad\Lib\Launchpad.ahk
#Include E:\Tools\Launchpad\Lib\Builder\AhkLauncherBuilder.ahk
#Include E:\Tools\Launchpad\Lib\Builder\BuilderBase.ahk
#Include E:\Tools\Launchpad\Lib\BuildFile\BuildFileBase.ahk
#Include E:\Tools\Launchpad\Lib\BuildFile\ComposableBuildFile.ahk
#Include E:\Tools\Launchpad\Lib\BuildFile\CopyableBuildFile.ahk
#Include E:\Tools\Launchpad\Lib\BuildFile\GameAhkFile.ahk
#Include E:\Tools\Launchpad\Lib\BuildFile\GameExeFile.ahk
#Include E:\Tools\Launchpad\Lib\BuildFile\IconFile.ahk
#Include E:\Tools\Launchpad\Lib\BuildFile\ShortcutFile.ahk
#Include E:\Tools\Launchpad\Lib\Cache\CacheBase.ahk
#Include E:\Tools\Launchpad\Lib\Cache\FileCache.ahk
#Include E:\Tools\Launchpad\Lib\Cache\ObjectCache.ahk
#Include E:\Tools\Launchpad\Lib\Config\AppConfig.ahk
#Include E:\Tools\Launchpad\Lib\Config\ConfigBase.ahk
#Include E:\Tools\Launchpad\Lib\Config\FileConfig.ahk
#Include E:\Tools\Launchpad\Lib\Config\IniConfig.ahk
#Include E:\Tools\Launchpad\Lib\Config\JsonConfig.ahk
#Include E:\Tools\Launchpad\Lib\Config\LauncherConfig.ahk
#Include E:\Tools\Launchpad\Lib\DataSource\ApiDataSource.ahk
#Include E:\Tools\Launchpad\Lib\DataSource\DataSourceBase.ahk
#Include E:\Tools\Launchpad\Lib\DataSourceItem\DataSourceItemBase.ahk
#Include E:\Tools\Launchpad\Lib\DataSourceItem\DSAssetFile.ahk
#Include E:\Tools\Launchpad\Lib\DataSourceItem\DSFile.ahk
#Include E:\Tools\Launchpad\Lib\DataSourceItem\DSJson.ahk
#Include E:\Tools\Launchpad\Lib\DataSourceItem\DSListing.ahk
#Include E:\Tools\Launchpad\Lib\Dependency\DependencyBase.ahk
#Include E:\Tools\Launchpad\Lib\Dependency\DownloadableDependency.ahk
#Include E:\Tools\Launchpad\Lib\Gui\DialogBox.ahk
#Include E:\Tools\Launchpad\Lib\Gui\FormWindow.ahk
#Include E:\Tools\Launchpad\Lib\Gui\GuiBase.ahk
#Include E:\Tools\Launchpad\Lib\Gui\LauncherEditor.ahk
#Include E:\Tools\Launchpad\Lib\Gui\MainWindow.ahk
#Include E:\Tools\Launchpad\Lib\Gui\ManageWindow.ahk
#Include E:\Tools\Launchpad\Lib\Gui\ProgressIndicator.ahk
#Include E:\Tools\Launchpad\Lib\Gui\SettingsWindow.ahk
#Include E:\Tools\Launchpad\Lib\Gui\SingleInputBox.ahk
#Include E:\Tools\Launchpad\Lib\Gui\ToolsWindow.ahk
#Include E:\Tools\Launchpad\Lib\HttpReq\HttpReqBase.ahk
#Include E:\Tools\Launchpad\Lib\HttpReq\WinHttpReq.ahk
#Include E:\Tools\Launchpad\Lib\LauncherGame\EditableLauncherGame.ahk
#Include E:\Tools\Launchpad\Lib\LauncherGame\LauncherGameBase.ahk
#Include E:\Tools\Launchpad\Lib\Notifier\NotifierBase.ahk
#Include E:\Tools\Launchpad\Lib\Notifier\ToastNotifier.ahk
#Include E:\Tools\Launchpad\Lib\Service\CacheManager.ahk
#Include E:\Tools\Launchpad\Lib\Service\DataSourceManager.ahk
#Include E:\Tools\Launchpad\Lib\Service\DependencyManager.ahk
#Include E:\Tools\Launchpad\Lib\Service\WindowManager.ahk
#Include E:\Tools\Launchpad\Lib\Service\LauncherManager.ahk
#Include E:\Tools\Launchpad\Lib\Service\NotificationService.ahk
#Include E:\Tools\Launchpad\Lib\Service\ServiceBase.ahk
#Include E:\Tools\Launchpad\Lib\Toolbar\ToolbarBase.ahk
#Include E:\Tools\Launchpad\Lib\Vendor\Jxon.ahk
; End of auto-generated includes.
