; Automatically-generated file. Manual edits will be overwritten.
#Include App\LaunchpadBuilder.ahk
#Include AppBuilder\AhkBinsBuilder.ahk
#Include AppBuilder\AhkExeBuilder.ahk
#Include AppBuilder\AppBuilderBase.ahk
#Include AppBuilder\ChocoPkgBuilder.ahk
#Include AppBuilder\LaunchpadOverlayBuilder.ahk
#Include AppBuilder\NsisInstallerBuilder.ahk
#Include BuildDeployer\ApiBuildDeployer.ahk
#Include BuildDeployer\BuildDeployerBase.ahk
#Include BuildDeployer\ChocoDeployer.ahk
#Include BuildDeployer\GitHubBuildDeployer.ahk
#Include BulkOperation\LaunchpadBuildOp.ahk
#Include BulkOperation\LaunchpadDeployOp.ahk
#Include Config\LaunchpadBuilderConfig.ahk
#Include Gui\BuildSettingsForm.ahk
#Include Gui\ReleaseInfoForm.ahk
#Include VersionIdentifier\GitTagVersionIdentifier.ahk
#Include VersionIdentifier\VersionIdentifierBase.ahk
