class WebServicesEvents {
    static WEB_SERVICES_HTTP_REQ_ALTER := 0x4200
    static WEB_SERVICES_REQUEST_PRESEND := 0x4210
    static WEB_SERVICES_CACHED_RESPONSE_CREATED := 0x4215
    static WEB_SERVICES_HTTP_RESPONSE_CREATED := 0x4217
    static WEB_SERVICES_RESPONSE_ALTER := 0x4220
}