name: example
description: Showcase App for Fluent UI package for Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.1.2
  provider: ^6.0.3
  system_theme: ^2.0.0
  window_manager: ^0.2.7
  flutter_acrylic: ^1.0.0+2
  url_strategy: ^0.2.0
  url_launcher: ^6.1.5
  clipboard: ^0.1.3
  email_validator: ^2.0.1
  http: ^0.13.4
  flutter_markdown: ^0.6.10+5
  flutter_syntax_view: 
    git:
      url: https://github.com/YehudaKremer/flutter_syntax_view.git
  dart_code_metrics: ^5.2.1
  path_provider: ^2.0.11
  auto_size_text: ^3.0.0
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2
  googleapis: ^9.2.0
  win32: ^3.1.3
  drift: ^2.3.0
  characters: ^1.2.1
  network_info_plus: ^3.0.1
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#42a5f5"
  image: web/assets/flutter_logo.png