name: launchpad_app
description: Showcase App for Fluent UI package for Flutter
publish_to: 'none'
version: 10.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  archive: ^3.3.5
  args: ^2.3.1
  async: ^2.9.0
  auto_size_text: ^3.0.0
  badges: ^2.0.3
  catcher: ^0.7.0
  characters: ^1.2.1
  chopper: ^6.0.0
  clipboard: ^0.1.3
  collection: ^1.16.0
  counter_button: ^1.0.1
  crypto: ^3.0.2
  dart_code_metrics: ^5.2.1
  dartx: ^1.1.0
  device_info_plus: ^7.0.1
  drift: ^2.3.0
  dropdown_search: ^5.0.5
  easy_localization: ^3.0.1
  email_validator: ^2.0.1
  expressions: ^0.2.4
  feedback: ^2.5.0
  file: ^6.1.4
  file_picker: ^5.2.4
  filesize: ^2.0.1
  firebase_auth: ^3.11.2
  firebase_auth_desktop: ^1.0.2
  firebase_core: ^1.24.0
  firebase_core_desktop: ^1.0.2
  filter_list: ^1.0.2
  fluent_ui: ^4.1.2
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.0.0+2
  flutter_hooks: ^0.18.5+1
  flutter_layout_grid: ^2.0.1
  flutter_markdown: ^0.6.10+5
  flutter_phoenix: ^1.1.0
  flutter_screenutil: ^5.6.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.6
  flutter_syntax_view: 
    git:
      url: https://github.com/YehudaKremer/flutter_syntax_view.git
  freezed_annotation: ^2.2.0
  github: ^9.7.0
  go_router: ^6.0.0
  google_fonts: ^3.0.1
  googleapis: ^9.2.0
  hooks_riverpod: ^2.1.1
  hotkey_manager: ^0.1.7
  http: ^0.13.5
  humanizer: ^2.0.0
  image: ^3.2.2
  image_picker: ^0.8.6
  image_picker_windows: ^0.1.0+3
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  json_annotation: ^4.7.0
  launch_at_startup: ^0.2.0
  local_auth: ^2.1.2
  local_notifier: ^0.1.5
  logger: ^1.1.0
  mime: ^1.0.3
  msix: ^3.7.0
  network_info_plus: ^3.0.1
  nil: ^1.1.1
  number_display: ^3.0.0
  once: ^1.5.0
  package_info_plus: ^3.0.2
  path: ^1.8.2
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  platform_info: ^3.2.0
  pool: ^1.5.1
  protobuf: ^2.1.0
  protocol_handler: ^0.1.4
  recase: ^4.1.0
  riverpod_annotation: ^1.0.6
  scroll_to_index: ^3.0.1
  shimmer: ^2.0.0
  stack_trace: ^1.10.0
  stock: ^1.0.1
  string_validator: ^0.3.0
  synchronized: ^3.0.0+3
  system_theme: ^2.0.0
  timeago: ^3.3.0
  tray_manager: ^0.2.0
  undo: ^1.4.0
  updat: ^1.2.0
  usage: ^4.1.0
  url_launcher: ^6.1.5
  url_strategy: ^0.2.0
  uuid: ^3.0.7
  version: ^3.0.2
  watcher: ^1.0.2
  webview_windows: ^0.2.2
  win32: ^3.1.3
  window_manager: ^0.2.7
  xml: ^6.1.0
  yaml: ^3.1.1
  windows_single_instance: ^0.1.5

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  faker: ^2.1.0
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  go_router_builder: ^1.0.15
  isar_generator: ^3.0.5
  json_serializable: ^6.5.4
  mockito: ^5.3.2
  pigeon: ^0.2.4
  riverpod_generator: ^1.0.6
  swagger_dart_code_generator: ^2.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/logo_wide.svg
    - assets/graphics/light/logo_wide.svg
    - assets/graphics/splash.png
    - assets/graphics/light/splash.png
    - assets/graphics/icon.png

flutter_gen:
  integrations:
    flutter_svg: true

flutter_icons:
  android:
    generate: false
  ios:
    generate: false
  image_path: "assets/graphics/icon.png"
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

flutter_native_splash:
  color: "#202020"
  image: assets/graphics/splash.png