; Automatically-generated file, do not edit manually.
#Include E:\Tools\Launchpad\Lib\Launchpad\Launchpad.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Builder\AhkLauncherBuilder.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Builder\BuilderBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\BuildFile\BuildFileBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\BuildFile\ComposableBuildFile.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\BuildFile\CopyableBuildFile.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\BuildFile\GameAhkFile.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\BuildFile\GameExeFile.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\BuildFile\IconFile.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\BuildFile\ShortcutFile.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\BulkOperation\BuildLaunchersOp.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\BulkOperation\BulkOperationBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\BulkOperation\CleanLaunchersOp.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\BulkOperation\LauncherGameOpBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\BulkOperation\LoadLaunchersOp.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\BulkOperation\ValidateLaunchersOp.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Cache\CacheBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Cache\FileCache.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Cache\ObjectCache.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Config\AppConfig.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Config\ConfigBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Config\FileConfig.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Config\IniConfig.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Config\JsonConfig.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Config\LauncherConfig.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\DataSource\ApiDataSource.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\DataSource\DataSourceBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\DataSourceItem\DataSourceItemBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\DataSourceItem\DSAssetFile.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\DataSourceItem\DSFile.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\DataSourceItem\DSJson.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\DataSourceItem\DSListing.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Dependency\DependencyBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Dependency\DownloadableDependency.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Entity\EntityBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Entity\LauncherEntity.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Entity\ManagedEntityBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Entity\ManagedGameEntity.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Entity\ManagedLauncherEntity.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Notifier\NotifierBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Notifier\ToastNotifier.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\OpError\BasicOpError.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\OpError\OpErrorBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\OpStatus\BasicOpStatus.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\OpStatus\OpStatusBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Service\BuilderManager.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Service\CacheManager.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Service\DataSourceManager.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Service\DependencyManager.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Service\InstallerManager.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Service\LauncherManager.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Service\NotificationService.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Service\ServiceBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Service\WindowManager.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Toolbar\ToolbarBase.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Window\DialogBox.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Window\FormWindow.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Window\LauncherEditor.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Window\MainWindow.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Window\ManageWindow.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Window\ProgressIndicator.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Window\SettingsWindow.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Window\SingleInputBox.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Window\ToolsWindow.ahk
#Include E:\Tools\Launchpad\Lib\Launchpad\Window\WindowBase.ahk
; End of auto-generated includes.
