; Automatically-generated file. Manual edits will be overwritten.
#Include App\Launchpad.ahk
#Include Builder\AhkLauncherBuilder.ahk
#Include Builder\BuilderBase.ahk
#Include Builder\BuildFile\BuildFileBase.ahk
#Include Builder\BuildFile\ComposableBuildFile.ahk
#Include Builder\BuildFile\CopyableBuildFile.ahk
#Include Builder\BuildFile\GameAhkFile.ahk
#Include Builder\BuildFile\GameExeFile.ahk
#Include Builder\BuildFile\IconFile.ahk
#Include Builder\BuildFile\ShortcutFile.ahk
#Include BulkOperation\DetectedGamesOp\AddDetectedGamesOp.ahk
#Include BulkOperation\DetectedGamesOp\DetectGamesOp.ahk
#Include BulkOperation\LauncherBuilderOp\BuildLaunchersOp.ahk
#Include BulkOperation\LauncherBuilderOp\CleanLaunchersOp.ahk
#Include BulkOperation\LauncherBuilderOp\LauncherBuilderOpBase.ahk
#Include BulkOperation\LauncherGameOp\LauncherGameOpBase.ahk
#Include BulkOperation\LauncherGameOp\ValidateLaunchersOp.ahk
#Include BulkOperation\LoadOp\LoadLaunchersOp.ahk
#Include BulkOperation\LoadOp\LoadPlatformsOp.ahk
#Include Config\LauncherConfig.ahk
#Include Config\LaunchpadConfig.ahk
#Include Config\PlatformsConfig.ahk
#Include ConfigMigrator\LaunchpadIniMigrator.ahk
#Include DetectedGame\DetectedGame.ahk
#Include Entity\LauncherEntity.ahk
#Include Entity\ManagedEntityBase.ahk
#Include Entity\ManagedGameEntity.ahk
#Include Entity\ManagedLauncherEntity.ahk
#Include Entity\PlatformEntity.ahk
#Include Events\LaunchpadEvents.ahk
#Include GamePlatform\BasicPlatform.ahk
#Include GamePlatform\GamePlatformBase.ahk
#Include GamePlatform\RegistryLookupGamePlatformBase.ahk
#Include Gui\Dialog\AboutWindow.ahk
#Include Gui\Dialog\AccountInfoWindow.ahk
#Include Gui\Dialog\LauncherDeleteWindow.ahk
#Include Gui\Dialog\LoginWindow.ahk
#Include Gui\EntityEditor\LauncherEditor.ahk
#Include Gui\EntityEditor\LauncherEditorBase.ahk
#Include Gui\EntityEditor\LauncherEditorSimple.ahk
#Include Gui\EntityEditor\ManagedEntityEditorBase.ahk
#Include Gui\EntityEditor\ManagedGameEditor.ahk
#Include Gui\EntityEditor\ManagedLauncherEditor.ahk
#Include Gui\EntityEditor\PlatformEditor.ahk
#Include Gui\Form\DetectedGameEditor.ahk
#Include Gui\Form\ImportShortcutForm.ahk
#Include Gui\Form\LauncherCreateFormBase.ahk
#Include Gui\Form\LauncherWizard.ahk
#Include Gui\Form\SettingsWindow.ahk
#Include Gui\Form\SetupWindow.ahk
#Include Gui\ManageWindow\DetectedGamesWindow.ahk
#Include Gui\ManageWindow\MainWindow.ahk
#Include Gui\ManageWindow\ManageBackupsWindow.ahk
#Include Gui\ManageWindow\ManageWindowBase.ahk
#Include Gui\ManageWindow\PlatformsWindow.ahk
#Include Installer\DependencyInstaller.ahk
#Include Installer\LaunchpadUpdate.ahk
#Include Locator\GameExeLocator.ahk
#Include Modules\Bethesda\Bethesda.module.ahk
#Include Modules\Bethesda\GamePlatform\BethesdaPlatform.ahk
#Include Modules\Blizzard\Blizzard.module.ahk
#Include Modules\Blizzard\GamePlatform\BlizzardPlatform.ahk
#Include Modules\Blizzard\StructuredData\BlizzardProductDb.ahk
#Include Modules\Epic\Epic.module.ahk
#Include Modules\Epic\GamePlatform\EpicPlatform.ahk
#Include Modules\LaunchpadApi\AuthProvider\LaunchpadApiAuthProvider.ahk
#Include Modules\LaunchpadApi\DataSource\ApiDataSource.ahk
#Include Modules\Origin\Origin.module.ahk
#Include Modules\Origin\GamePlatform\OriginPlatform.ahk
#Include Modules\Riot\Riot.module.ahk
#Include Modules\Riot\GamePlatform\RiotPlatform.ahk
#Include Modules\Steam\Steam.module.ahk
#Include Modules\Steam\GamePlatform\SteamPlatform.ahk
#Include Service\BuilderManager.ahk
#Include Service\LauncherManager.ahk
#Include Service\PlatformManager.ahk
#Include State\LaunchpadAppState.ahk
