; Automatically-generated file, do not edit manually.
#Include Launchpad.ahk
#Include AuthProvider\LaunchpadApiAuthProvider.ahk
#Include Builder\AhkLauncherBuilder.ahk
#Include Builder\BuilderBase.ahk
#Include Builder\BuildFile\BuildFileBase.ahk
#Include Builder\BuildFile\ComposableBuildFile.ahk
#Include Builder\BuildFile\CopyableBuildFile.ahk
#Include Builder\BuildFile\GameAhkFile.ahk
#Include Builder\BuildFile\GameExeFile.ahk
#Include Builder\BuildFile\IconFile.ahk
#Include Builder\BuildFile\ShortcutFile.ahk
#Include BulkOperation\AddDetectedGamesOp.ahk
#Include BulkOperation\BuildLaunchersOp.ahk
#Include BulkOperation\BulkOperationBase.ahk
#Include BulkOperation\CleanLaunchersOp.ahk
#Include BulkOperation\DetectGamesOp.ahk
#Include BulkOperation\InstallOp.ahk
#Include BulkOperation\LauncherBuilderOpBase.ahk
#Include BulkOperation\LauncherGameOpBase.ahk
#Include BulkOperation\LoadLaunchersOp.ahk
#Include BulkOperation\LoadModulesOp.ahk
#Include BulkOperation\LoadPlatformsOp.ahk
#Include BulkOperation\UpdateOp.ahk
#Include BulkOperation\ValidateLaunchersOp.ahk
#Include Config\AppConfig.ahk
#Include Config\BlizzardProductDb.ahk
#Include Config\ConfigBase.ahk
#Include Config\FileConfig.ahk
#Include Config\IniConfig.ahk
#Include Config\JsonConfig.ahk
#Include Config\LauncherConfig.ahk
#Include Config\PlatformsConfig.ahk
#Include Config\ProtoConfig.ahk
#Include DataSource\ApiDataSource.ahk
#Include DetectedGame\DetectedGame.ahk
#Include Entity\EntityBase.ahk
#Include Entity\LauncherEntity.ahk
#Include Entity\ManagedEntityBase.ahk
#Include Entity\ManagedGameEntity.ahk
#Include Entity\ManagedLauncherEntity.ahk
#Include Entity\PlatformEntity.ahk
#Include Events\LaunchpadEvents.ahk
#Include GamePlatform\BasicPlatform.ahk
#Include GamePlatform\BethesdaPlatform.ahk
#Include GamePlatform\BlizzardPlatform.ahk
#Include GamePlatform\EpicPlatform.ahk
#Include GamePlatform\GamePlatformBase.ahk
#Include GamePlatform\OriginPlatform.ahk
#Include GamePlatform\RegistryLookupGamePlatformBase.ahk
#Include GamePlatform\RiotPlatform.ahk
#Include GamePlatform\SteamPlatform.ahk
#Include Installer\DependencyInstaller.ahk
#Include Installer\LaunchpadUpdate.ahk
#Include Installer\ThemeInstaller.ahk
#Include Module\ModuleBase.ahk
#Include Service\AppComponentServiceBase.ahk
#Include Service\AppServiceBase.ahk
#Include Service\AuthService.ahk
#Include Service\BuilderManager.ahk
#Include Service\CacheManager.ahk
#Include Service\EntityManagerBase.ahk
#Include Service\InstallerManager.ahk
#Include Service\LauncherManager.ahk
#Include Service\ModuleManager.ahk
#Include Service\NotificationService.ahk
#Include Service\PlatformManager.ahk
#Include Service\ThemeManager.ahk
#Include Service\WindowManager.ahk
#Include Window\AboutWindow.ahk
#Include Window\AccountInfoWindow.ahk
#Include Window\DetectedGameEditor.ahk
#Include Window\DetectedGamesWindow.ahk
#Include Window\EntityDeleteWindow.ahk
#Include Window\EntityEditorBase.ahk
#Include Window\LauncherDeleteWindow.ahk
#Include Window\LauncherEditor.ahk
#Include Window\LauncherWizard.ahk
#Include Window\LaunchpadFormGuiBase.ahk
#Include Window\LaunchpadGuiBase.ahk
#Include Window\LoginWindow.ahk
#Include Window\MainWindow.ahk
#Include Window\ManagedEntityEditorBase.ahk
#Include Window\ManagedGameEditor.ahk
#Include Window\ManagedLauncherEditor.ahk
#Include Window\ManageWindow.ahk
#Include Window\ManageWindowBase.ahk
#Include Window\PlatformEditor.ahk
#Include Window\PlatformsWindow.ahk
#Include Window\SettingsWindow.ahk
#Include Window\SetupWindow.ahk
#Include Window\ToolsWindow.ahk
; End of auto-generated includes.
